### ISSUE TITLE
Rename destroyed to unmounted

### ISSUE THREAD

**Issue by mattkingshott** [Norserium/vue-advanced-cropper#114]
I'm getting warnings on the version / branch targeting Vue 3:

```javascript
[Vue warn]: `destroyed` has been renamed to `unmounted`
```

**Comment by Norserium** [comment]
@mattkingshott, thank you for your report. Fixed in `2.2.1`.

**Comment by Norserium** [comment]
@mattkingshott, will I close issue then. If you encounter one in the future, feel free to reopen.

**Comment by TheVaan** [comment]
Hello @Norserium, it seems you missed one line:
https://github.com/Norserium/vue-advanced-cropper/blob/c3f6c5bd2d446dbf995b3347c3f956d4aec73eaa/src/components/helpers/Preview.vue#L164
