### ISSUE TITLE
Persistant CORs error while using cropper

### ISSUE THREAD

**Issue by rhysstubbs** [Norserium/vue-advanced-cropper#44]
I have a web app fetching images cross-origin. The server that is serving those images is configured to allow cross-origin requests and I can see the images in various places. However, when I try and load that image using the cropper I suddenly get failed CORs requests.

In the source I can see you're checking if the image src URL is cross origin, and if so then setting the anonymous flag for the canvas so it isn't in "taint" mode. Before I jump any further into the source looking for the problem, is this expected/a known issue?

**Comment by Norserium** [comment]
Hello, @rhysstubbs!

Please provide the response headers. If you have got no 'Access-Control-Allow-Origin' in the image loading response header, you can't get the access to content of the canvas (it will be tainted).

**Comment by rhysstubbs** [comment]
@Norserium, Hi!

Sorry I should have updated the issue/added a comment. So after writing that I tested with disabling cache in my browser (Chrome) and thereafter I stopped receiving the CORs errors. The images 100% have the correct CORs related headers and loading multiple times prior to being used in the Cropper component. Was disabling the cache a coincedence or could that be the reason?

**Comment by Norserium** [comment]
@rhysstubbs, I should notice, that if images loaded correctly, it doesn't mean that they had correct headers. The problems will appear only if you try to work with their internal content (for example, draw at a canvas).

**Comment by rhysstubbs** [comment]
![Screenshot from 2020-04-08 12-43-16](https://user-images.githubusercontent.com/17863822/78775477-916b3900-7996-11ea-98b5-c6504a4666b6.png)

**Comment by Norserium** [comment]
@rhysstubbs, I suppose, that there might be a problem with cache, and I should add timestamp to all crossorigin requests to prevent their caching.

**Comment by Norserium** [comment]
@rhysstubbs, I suppose, that there might be a problem with cache. Could you provide the link to image (perhaps with hidden domain, it doesn't matter right now)?

**Comment by Norserium** [comment]
@rhysstubbs, any news?

**Comment by mkaliberda** [comment]
@Norserium  Hi, I have the same problem. 
In my case, I'm getting an  error because the cropper send the request to HTTP instead of HTTPS
![image](https://user-images.githubusercontent.com/19783885/79042561-7b14e580-7c01-11ea-9ca4-ea343c528268.png)

**Comment by Norserium** [comment]
@mkaliberda, could you provide the part of your code?

**Comment by mkaliberda** [comment]
Thanks for answer
Yes, sure
```<cropper
              v-if="imageUrl"
              class="avatar"
              :src="imageUrl"
              :stencilProps="{
                aspectRatio: 12/12
              }"
              @change="change"
          ></cropper>```
It's hepen when I set Image Url fist time after component is loaded

There is the method for handle change
```    async change(data) {
      if (this.imageCroppedUrl) {
        data.canvas.toBlob((blob) => {
          this.profileData.avatar = new File([blob], `${this.profileData.email}_avatar.png`);
        }, 'image/png', 1);
        this.imageCroppedUrl = data.canvas.toDataURL('image/png');
      }
    },```

and for ``` addAttachment(request) {
      this.imageUrl = URL.createObjectURL(request.file);
      this.profileData.avatar = request.file;
    },
    clearAvatar() {
      this.imageUrl = null;
      this.imageCroppedUrl = null;
    },```

**Comment by Norserium** [comment]
@mkaliberda, how do you invoke `addAttachment` method? What is `request` object? What protocol do you use for the site, where cropper is used?

**Comment by mkaliberda** [comment]
addAttachment methods work fine
The site working in https and axios has https protocol too.
This error happen before when I try to set a default imageUrl, it's URL that return API
And I've check it. 
The problem in the back-end))

![image](https://user-images.githubusercontent.com/19783885/79043010-00e66000-7c05-11ea-87a1-9a665cbfac12.png)

Thank you for your time!

**Comment by Norserium** [comment]
@mkaliberda, you are welcome!

**Comment by Norserium** [comment]
@rhysstubbs, I suppose some changes in `0.16.2` can affect and solve your problem.

**Comment by rhysstubbs** [comment]
@Norserium Thanks, I will take a look

**Comment by Norserium** [comment]
@rhysstubbs, adding the cache busting leads to another problems with different services, so I rolled away that changes. Please provide the link to the image to reproduce this problem and advice you actual solution.

**Comment by chokies** [comment]
experiencing this issue with the current version using s3 end points. My cropper had a v-if and and image is already cached.

**Comment by Norserium** [comment]
@chokies, could you provide additional data? The link to image? Codesandbox that illustrates your problem?

**Comment by bribar** [comment]
Hi @Norserium 

I have the same issue loading images from Amazon s3 buckets. It loads fine not using Cropper (check screenshot, third entry is 200 response).

I have a CORS policy set for my domain in s3 bucket...

![image](https://user-images.githubusercontent.com/10064729/85317806-db32ce00-b473-11ea-9b6b-201b7085173e.png)

I tried exposing the Access-Control-Allow-Origin header but doesn't come across in request. I've tried changing AllowedHeader to this `<AllowedHeader>Authorization</AllowedHeader>`. I've tried clearing cache.

![image](https://user-images.githubusercontent.com/10064729/85318052-3369d000-b474-11ea-98b3-f0d9e2898216.png)

![image](https://user-images.githubusercontent.com/10064729/85318636-2b5e6000-b475-11ea-9eeb-10683fbde8b3.png)

Nothing seems to work. Any ideas on how to include it in the response headers from AWS s3?

This seems like a really cool plugin but not useful if I can't get past this.

**Comment by bribar** [comment]
I found this...
https://intellipaat.com/community/24967/s3-not-returning-access-control-allow-origin-headers,
but I think this would be the responsibility of the plugin.

Or is there an option/parameter to accomplish this?

**Comment by bribar** [comment]
@rhysstubbs I see you use AmazonS3, how are you getting the headers returned? Is it because you use CloudFront?

**Comment by Norserium** [comment]
@bribar, I do not see 'access-control-allow-origin' header in your response.
![image](https://user-images.githubusercontent.com/9862719/85326752-7492cc00-b4d6-11ea-9868-0bdc4ee6e978.png)

You can try to change the following line in your rules `<AllowedOrigin>MyDomainHere</AllowedOrigin>` to `<AllowedOrigin>*</AllowedOrigin>`.

In any case I currently suppose that it's not the problem of my library and you will encounter this problem every time when you try to process image's content.

**Comment by bribar** [comment]
Yeah I know...Amazon s3 doesn't return it unless you make sure that you use an Origin header with every request.

> I found this...
> https://intellipaat.com/community/24967/s3-not-returning-access-control-allow-origin-headers,
> but I think this would be the responsibility of the plugin.
> 
> Or is there an option/parameter to accomplish this?

Your plugin is requesting those images through xhr correct? Does it send Origin in the request?

I'm not sure how to get the header in the response from Amazon.

**Comment by rhysstubbs** [comment]
> @rhysstubbs I see you use AmazonS3, how are you getting the headers returned? Is it because you use CloudFront?

Funnily enough I’m still experiencing problem with this CORs issue, but I haven’t given it any attention since I originally posted this issue. I will however take a look at this tomorrow as it’d be good to fix. If I come across anything I will make sure to comment here with the details. I am using CloudFront, yes.

**Comment by Norserium** [comment]
@bribar, could you provide any link on image at your server?

**Comment by rhysstubbs** [comment]
> Yeah I know...Amazon s3 doesn't return it unless you make sure that you use an Origin header with every request.
> 
> > I found this...
> > https://intellipaat.com/community/24967/s3-not-returning-access-control-allow-origin-headers,
> > but I think this would be the responsibility of the plugin.
> > Or is there an option/parameter to accomplish this?
> 
> Your plugin is requesting those images through xhr correct? Does it send Origin in the request?
> 
> I'm not sure how to get the header in the response from Amazon.

You are correct, Amazon does not return the CORs headers unless a Origin header is specified on the request. I am going to test this locally and perhaps put in a PR if I find a stable fix.

**Comment by rhysstubbs** [comment]
FYI;
I've forked this repo and I am currently testing the fix I've applied. In a few days once I'm confident it's working I will submit a PR :)

**Comment by chokies** [comment]
actually i wasnt sure how i fixed it. its was either adding the cors policy on aws or removing the v-if that i added that hides the cropper. But playing with the hard reload/clear cache thing before sometimes fixes the issue. But then im really not sure. Also im not experiencing it anymore

**Comment by bribar** [comment]
Hi @chokies 

If I disable cache (while dev tools open) the header error doesn't come up. If I close dev tools it will appear again on refresh. But it's still an issue for the end user, who won't be using dev tools or clearing cache every time.

Can you share your CORS policy? I have that set up too, but doesn't seem to help.

@rhysstubbs I look forward to your fix!

**Comment by Norserium** [comment]
@bribar, alas, I can't reproduce the error until somebody provide me the link to such images. I use the images from other domain in the documentation and don't encounter any problems.

Did you try to set `checkOrientation` to `false`?

**Comment by bribar** [comment]
@Norserium Interestingly enough, I went to get an image url for you and noticed it's not loading with errors now, WTH haha. I see the response headers now have the correct headers. I don't know what changed.

Maybe CORS policy updates on Amazon take a while to reflect changes? I did upload a different image, maybe CORS update didn't apply to old image that existed prior to update. I have no clue.

I'll see if it pops up again.

**Comment by bribar** [comment]
@Norserium It's happening with this image...

https://s3-us-west-1.amazonaws.com/yalla.resources/images/clients/random_9.jpg

**Comment by Norserium** [comment]
@bribar, thanks! But I can't reproduce this error with your link right now. I've already tried in Chrome and Firefox (with enabled and disabled cache).

**Comment by rhysstubbs** [comment]
> @Norserium It's happening with this image...
> 
> https://s3-us-west-1.amazonaws.com/yalla.resources/images/clients/random_9.jpg
> 
> checkOrientation to false removes one of the errors but the Cropper image doesn't show.

Have you read through the AWS docs [Troubleshooting CORS issues](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors-troubleshooting.html)? This is definitely an AWS S3 issue, you were right when you previously mentioned the Origin header needs to be specified. The cropper looks to make more than 1 request for the image, if you inspect I expect you find most are sucessful and only 1 is failing?

**Comment by Norserium** [comment]
@rhysstubbs, yes you are right, but I decide to drop this feature, cause the library user can do it himself by adding timestamp to `src`.

Alas, I can't fix this problem until I get some image, that can be used to reproduce it. But again, I've used much images from external resources at the documentation and don't encounter any problems.

**Comment by chokies** [comment]
this is my cors config on aws bucket

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>

**Comment by mcpeakdb** [comment]
I can reproduce this whenever I put the tags within a v-if statement. Otherwise, the same image works. I don't think the issue is with images, but some behavior with the component when contained within a v-if block.

**Comment by Norserium** [comment]
@mcpeakdb could you create the codesandbox, that reproduces your problem?

**Comment by mcpeakdb** [comment]
@Norserium i'll do my best when i'm back at my computer tomorrow. Essentially, I had a v-if block where the comparison returns false, so the cropper is hidden on page load. When changing the data to have the comparison return true to unhide the cropper, I receive the CORS error. Removing the v-if check or changing my code to have the comparison return true on page load (showing the cropper on page load) both work, as intended.

Please stand by! 👍

**Comment by mcpeakdb** [comment]
Hi @Norserium, of course I can't reproduce it in the sandbox (isn't that always how this goes?). I'll see if I can try to determine if there is something special about my environment, sorry this wasn't helpful.

**Comment by alibabaazimi** [comment]
Hi @Norserium , I am using google cloud storage (bucket) and cropper does not appear. Can you help me please. I use laravel and vue. and and this is the content of my cors.php: 
`    'paths' => ['api/*'],

    'allowed_methods' => ['*'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => ['*'],

    'max_age' => 0,

    'supports_credentials' => false,`

**Comment by Norserium** [comment]
@alibabaazimi, what does mean "cropper does not appear"? Do you encounter any errors in the console? Could you provide the link to the image?

**Comment by alibabaazimi** [comment]
![Screen Shot 2020-11-28 at 7 50 49 AM](https://user-images.githubusercontent.com/13467999/100492872-85630000-314e-11eb-92c8-5da2a0e0cfbc.png)

**Comment by alibabaazimi** [comment]
![Screen Shot 2020-11-28 at 7 57 43 AM](https://user-images.githubusercontent.com/13467999/100492940-7df02680-314f-11eb-8701-0aa5ee973c2c.png)

**Comment by Norserium** [comment]
@alibabaazimi, I suppose, that it's not the problem of this library. To access to the image content server should return the appropriate [`Access-Control-Allow-Origin`](https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%97%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B8/Access-Control-Allow-Origin) header, but it doesn't return it now.

If you crop the image on your server you can set `canvas` prop to `false` and image will be loaded successful, otherwise you should configure your storage correctly (perhaps it is described in [this section](https://cloud.google.com/storage/docs/configuring-cors)).

**Comment by Norserium** [comment]
I've tested [image from your website](https://storage.googleapis.com/negah-296822.appspot.com/post_photos/336tSHFDFbS2OLXDz0sRENM47M5Zb5wIBbGX1AO9.jpeg) in other croppers also. Same problem.

**Comment by alibabaazimi** [comment]
Thanks for your considering. I have found the problem and it is solved now. Google cloud has its own CORS settings for its bucket. Again thank you so much

**Comment by Norserium** [comment]
@alibabaazimi, you are welcome!

**Comment by Norserium** [comment]
I wrote [the short section about CORS](https://norserium.github.io/vue-advanced-cropper/guides/cross-origin.html) for the documentation. I hope it would be helpful.

**Comment by alexfauquette** [comment]
Hi @Norserium ,

Thanks for this super library. I have a problem with CORS.

## My problem
I set the `canvas` props to `false`. However, the <img> is unable to have access to the content due to the `crossorigin="anonymous"`.

## How to reproduce
```
<cropper
            class="cropper"
            :src="image_url"
            @change="changeCropCoordinate"
            :canvas="false"
          />
```

An example of URL used :
https://static.openfoodfacts.org/images/products/842/314/800/0015/nutrition_es.3.400.jpg

## suggestion

If I manually remove the `crossorigin="anonymous"` every thing works fine. I propose to add a props `useCrossOrigin` such that is `useCrossOrigin` is `false`, the image does not have the attribute `crossorigin`.

**Comment by Norserium** [comment]
@alexfauquette it can be considered as a bug. 

I don't see any reason to set `crossorigin` attribute when `canvas` is set to `false`. 

I assume that the best decision is the following:
1. I will add `crossorigin` prop that would accept the following values: `false`, `true`, `"anonymous"`, `"use-credentials"`.
2. The default value of `crossorigin` will depends on `canvas` props. If `canvas` is equal to `true` then `crossorigin` is equal to `true` ("anonymous") and vice versa.

I cannot say when I will implement it, but I try to eliminate the `crossorigin` attribute when `canvas` is equal to `false` today.

**Comment by alexfauquette** [comment]
Thanks :)

**Comment by Norserium** [comment]
@alexfauquette try to update to `1.4.0`.  [The example](https://codesandbox.io/s/vue-advanced-cropper-crossorigin-example-c6db3?file=/src/App.vue). Notice, that for your case you should disable the checking of an image orientation.

**Comment by alexfauquette** [comment]
It works perfectly :)

**Comment by Norserium** [comment]
I assume that after all this issue can be closed. The browser behavior that causes this issue is explained in the documentation [section](https://norserium.github.io/vue-advanced-cropper/guides/cross-origin.html).

**Comment by Getz85** [comment]
Hi @Norserium,

I still have issue with CORS on vue-advanced-cropper@next (2.7.0) for vuejs 3, with or without canvas set to false.

I use the same image that the exemple above:

```HTML
<cropper src="http://static.openfoodfacts.org/images/products/842/314/800/0015/nutrition_es.3.400.jpg"
         class="responsive photo"
         :check-orientation="false"
         :canvas="false"
         @change="onChange"
/>
```

And in the console:

> Access to image at 'http://static.openfoodfacts.org/images/products/842/314/800/0015/nutrition_es.3.400.jpg' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If I inspect the DOM of the cropper and remove the attribute "crossorigin" (which is set to false without canvas and anonymous with canvas) of the img tag, the image is displayed.

Is it a bug that was fixed on 1.4.0 and not reported on the next branch ?

**Comment by Norserium** [comment]
@Getz85, thank you for your report. Conditional rendering of attributes changed in Vue 3 ([official information](https://v3.vuejs.org/guide/migration/attribute-coercion.html#overview), [example](https://stackoverflow.com/a/64598898)), and I forget to adapt the code to its changes.

I've fixed it in `2.7.1` now.

**Comment by Getz85** [comment]
@Norserium 
I confirm that the problem is solved, thank you for your reactivity and thanks for this awesome module !

**Comment by Norserium** [comment]
@Getz85, you are welcome!

**Comment by sanjils** [comment]
if you are getting cors issue just use checkCrossOrigin={false}

My code looks like this:

`<Cropper
            ref={cropperRef}
            style={{ height: 400, width: '100%' }}
            aspectRatio={2 / 1}
            src={
              image?.path
                ? `${config.S3BucketURL}/${image.path}`
                : URL.createObjectURL(image)
            }
            viewMode={1}
            minCropBoxHeight={10}
            minCropBoxWidth={10}
            background={false}
            responsive={true}
            autoCropArea={1}
            checkOrientation={false}
            guides={true}
            checkCrossOrigin={false}
          />`

**Comment by khamaileon** [comment]
I'm using vue-advanced-cropper 1.11.7 on Vue 2. I had to turn [canvas](https://advanced-cropper.github.io/vue-advanced-cropper/components/cropper.html#props) to false to make it work.

**Comment by ZLY-gif** [comment]
I ran into the same issue and finally figured out the cause.·！
In my case, I first load images from the server using a plain <img> tag, and then select one to crop with Cropper. The problem is that the initial <img> loads without any attributes, which makes it a simple cross-origin resource embed. The browser allows it by default, so the request is sent without an Origin header. Even though the server is configured for CORS, without an Origin the response won’t include any CORS headers.
 As a result, the image is cached without CORS headers. Later, when Cropper tries to use it with crossOrigin = 'anonymous', the browser does send an Origin header, but the cached response doesn’t contain the required CORS headers—causing the error.
This also explains why disabling the cache makes the problem disappear: every request includes an Origin, the server responds with CORS headers, and everything works fine.
✅ Solution: add crossOrigin="anonymous" when initially loading the image. This ensures the first request already includes Origin, the server returns the proper CORS headers, and subsequent Cropper usage works without issues.

**Comment by vickyleon** [comment]
Hi, I had the same CORS issue with S3.
I added crossOrigin="anonymous", but it still failed sometimes.

What I noticed is that it was related to caching — when caching was disabled, it worked fine.
So my final solution was to add a parameter to the image URL so that the browser treats it as a different image:

`selectedImageUrl.value = `${url}?t=${new Date().getTime()}`;`
